### ISSUE TITLE
左右滑动不是很流畅

### ISSUE THREAD

**Issue by LIANGWEIBIAO** [chjtx/JRoll#11]
要拖动很大距离才能滑动，类似PhotoSwipe这么流畅就好了、

**Comment by chjtx** [comment]
你说的是JRoll的图集查看器吧，体现确实没PhotoSwipe好，感谢反馈。还有demo的第4张图800多k，用微信一看就崩了

**Comment by LIANGWEIBIAO** [comment]
0

**Comment by chjtx** [comment]
已解决

1、JRoll更新到2.4.6，在scroller添加了touch-action:none样式，解决了微信端缩放卡死的问题（原来不是图片过大的原因）

2、JRoll-Viewer更新到0.2.1，优化左右滑动体验，解决拖动距离过大的问题
