### ISSUE TITLE
jroll-viewer实例化两个以上用不了问题；

### ISSUE THREAD

**Issue by LIANGWEIBIAO** [chjtx/JRoll#13]
new JRollViewer('.viewer0')
   new JRollViewer('.viewer1')

实例化后第一个能容器的图片能正常滑动，第二个就不行，而且发出警告为；
Unable to preventDefault inside passive event listener due to target being treated as passive

#demo地址
https://git.coding.net/lamber0808/viewer.git
JRoll-master/plugins/jroll-viewer/2.html

帮忙看看什么问题，谢谢；

**Comment by chjtx** [comment]
方案一：整页使用JRoll滑动，不让body滑动，即body.scrollTop始终为0

方案二：修改JRoll源码

将jroll.js的_doScroll方法里用于解决垂直滑动超出屏幕边界的代码删掉，如下
```js
    _doScroll: function (d, e) {
      var me = this
      var pageY
      me.distance = d
      if (me.options.bounce) {
        me.x = me._compute(me.x, me.minScrollX, me.maxScrollX)
        me.y = me._compute(me.y, me.minScrollY, me.maxScrollY)
      }
      me.scrollTo(me.x, me.y, 0, me.options.bounce, null, true, (e.touches || [e]))
      me._execEvent('scroll', e)

//    // 解决垂直滑动超出屏幕边界时捕捉不到touchend事件无法执行结束方法的问题
//       if (e && e.touches) {
//         pageY = e.touches[0].pageY
//         if (pageY <= 10 || pageY >= window.innerHeight - 10) {
//           me._end()
//         }
//       }
    },
```

方案三：等我想到更好的法子更新插件

**Comment by chjtx** [comment]
方案三出来了，JRoll更新到v2.4.7添加edgeRelease选项，JRoll-Viewer更新到0.2.2，设edgeRelease选项为false
