### ISSUE TITLE
仿QQ列表侧滑删除的bug

### ISSUE THREAD

**Issue by CR-pcs** [chjtx/JRoll#14]
当scroller的行数量多起来后，在上下滑动的途中，再上下滑动时，会瞬间回到顶部/底部
官网上的demo也存在同样的问题
解决方案：
    在子jroll对象的scrollStart事件中，给父jroll对象的moving设值为false，就ok了
     j.on("scrollStart", function(e) { jroll.moving=false;}
希望作者能解决下这个bug

**Comment by chjtx** [comment]
非常感谢反馈，已在jroll.2.4.8里修复了该问题，并连同“当内层jroll将滑动权交给外层jroll后，再次触碰不能停住外层jroll”的问题一并修复了
