### ISSUE TITLE
感觉回弹的效果不太好。

### ISSUE THREAD

**Issue by afenghy** [chjtx/JRoll#17]
能否做成缓动的？减速的那种。准备把你的滚动插件集成到我的一个开源项目中。

**Comment by chjtx** [comment]
缓动？是啥样子？是说现在收起的速度太快吗？由于为了让它能在Android上滚起上万个dom，所以取用了requestAnimationFrame+translate来自己计算滚动效果，这个算法的优化也一直在研究着

**Comment by afenghy** [comment]
看到一个朝气蓬勃的国产滚动插件，我很欣慰。继续加油！

**Comment by chjtx** [comment]
@afenghy v2.4.9版本放慢了回弹速度，感觉应该会好点

**Comment by afenghy** [comment]
@chjtx 嗯，感觉是好多了。

因为没有详细看代码，从效果上看，比如手指往下滑，感觉是先滚动到0，然后再滚到一个正数的值，然后再回归到0。这个过程有点中断。

我想可不可以这样：先获得手指离开屏幕最后一段时间（如100-200毫秒）内移动的距离，算出最后的速度。再根据速度的衰减，得到停下来时的距离。再通过CSS3的缓动效果来实现滚动。
页面往下滚到顶，Y=0，如果大于0，则弹回到0 。
也就是如果用力比较大，会直接滚动到一个正数值，然后再回滚到0 。

因为没有仔细看代码。如果意见不一定好。仅供参考。
