### ISSUE TITLE
可以做一个类似天猫的 上拉加载商品详情 下拉返回商品介绍的demo吗? 

### ISSUE THREAD

**Issue by x1nGoo** [chjtx/JRoll#18]
可以做一个类似天猫的 上拉加载商品详情 下拉返回商品介绍的demo吗?  
自己试用了下 没做成功, 只完成了上拉加载商品详情 , 然后不知道怎么把弹性边界限定在这个div.
下拉后再返回

**Comment by chjtx** [comment]
```js
jroll.on('touchEnd', function(){
  if (this.y > 50) {
    // 返回商品介绍页
  }
})
```
下拉距离大于50px时返回端口介绍页，只能帮到这里了兄弟
