### ISSUE TITLE
在华为Honor（CHM-CL00）机上滑不动

### ISSUE THREAD

**Issue by afenghy** [chjtx/JRoll#19]
华为Honor型号是CHM-CL00，浏览器UC。但系统浏览器可以。
随后我让公司同事帮测，三星。红米。oppo及其他杂牌机也可以。不知道华为那个是不是特例。

**Comment by chjtx** [comment]
> 在UC浏览器上表现较差，作者已将UC浏览器定义为资讯类应用，非专业浏览器，不会专门去兼容它

这是官网上的一句话，抱歉了
