### ISSUE TITLE
vue 使用问题

### ISSUE THREAD

**Issue by HopeFE** [chjtx/JRoll#20]
JRoll得功能挺强大得，想在Vue项目中使用，但是看了vue得DEMO 在单页面应用中这样操作起来比较麻烦啊。希望作者能提供一个组件化得方式，类似与[vue-infinite-loading](https://github.com/PeachScript/vue-infinite-loading)。

**Comment by chjtx** [comment]
jroll-vue-infinite就是为Vue写的无限加载组件：[jroll-vue-infinite](https://github.com/chjtx/JRoll/tree/master/extends/jroll-vue-infinite)

```js
Vue.component('jroll-infinite', JRoll.VueInfinite(...))
```

自行封装成全局组件，可灵活的将自定义function传进JRoll.VueInfinite的bottomed选项执行异步数据加载

**Comment by i-nodejs** [comment]
上拉加载更多，更新dom的时候会闪烁，效果就像“把之前的dom也删除，再次创建了。而不是只创建新增的”。请大大指教，我是使用的不对吗？
![image](https://cloud.githubusercontent.com/assets/15365656/25610536/2e393e0a-2f56-11e7-8e74-a582ad1a6364.png)
var data1=[{cont:[{url:'images/video_bg1.png'}]},{cont:[{url:'images/video_bg2.png'},{url:'images/video_bg2.png'}]}];
