### ISSUE TITLE
关于插件jroll-viewer提一个建议

### ISSUE THREAD

**Issue by tanranran** [chjtx/JRoll#23]
1.传递图片链接,打开单张图片.的功能. 例如

var viewer=new JRollViewer({zoomMax:3,JRoll:window.JRoll});
viewer.show("https://cloud.githubusercontent.com/assets/5227840/25881705/11d43ef6-3571-11e7-9995-62924c3c1c03.png");

这种功能一般在那种动态创建图片的时候,会用到.打开单张图片的情况.

**Comment by chjtx** [comment]
你可以动态创建图片，也可以动态创建JRollViewer实例

```html
<div id="div">
  <img src="1.jpg"/>
</div>
```

```js
var viewer = new JRollViewer('#div')
var img = document.createElement('img')
img.src = '2.jpg'
img.setAttribute('jroll-viewer-image', '')
document.getElementById('div').appendChild(img)
viewer.show(1)
```
如果你想你的图集只有一张图片，div里不预先存放img就可以了

**Comment by tanranran** [comment]
非常感谢,解决了.
