### ISSUE TITLE
页面数据发生变化的时候，jroll的高度未能实时变化

### ISSUE THREAD

**Issue by fanweidong** [chjtx/JRoll#25]
当前页面已经 加载多页数据的时候，此时由于外部原因，导致页面数据发生变化，数据量减少的时候，jroll的高度怎么才能实时变化呢？现在碰到的情况是，组件不能自动滑动到有数据的位置，显示大量空白，需要自己手动上滑到 有数据的位置才能看到数据，此种情况改如何解决呢？

**Comment by chjtx** [comment]
当页面数据发生变化时用`jroll.refresh()`这个方法刷新就可以了

**Comment by fanweidong** [comment]
我用的是 jroll-vue-infinite 这个组件 ，在外部主动刷新的时候怎么 获取到 jroll这个对象？ （原谅我是个小小白（-_-!!））

**Comment by chjtx** [comment]
可以使用ref属性获取到

```html
<jroll-infinite ref="jrollscroller">
    <div class='item' v-for="i in items">{{i.index}}、{{i.text}}</div>
</jroll-infinite>
```

```js
{
  mounted: function () {
    console.log(this.$refs)
  }
}
```

可以看到`this.$refs`里有`jrollscroller`，`jrollscroller`里有`jroll`，嗯，这个`jroll`就是你要获取的对象

**Comment by fanweidong** [comment]
非常感谢，总算是解决了我的困扰，不过我发现 在我描述的场景中使用jroll.refresh()方法没什么作用，不能很好的解决这个问题，我是用jroll.scrollTo()来更新的。
