### ISSUE TITLE
页面滚动区域中间部分有三个导航按钮 滑动问题

### ISSUE THREAD

**Issue by wafj999** [chjtx/JRoll#26]
我都页面的滚动区域中间位置设置了一排三个 分类显示按钮 当点击按钮的时候 我执行了scrollTo方法到这个位置 没问题 但是当 我把页面 滑动一下再点击这个按钮滚动就乱跳了开始 有什么思路吗？我scrollto到的是按钮那一排div的.offset().top这个值

**Comment by chjtx** [comment]
这样描述太模糊了，建议在 [http://runjs.cn/](http://runjs.cn/) 这个网站把你的例子放上去，然后将生成的链接发出来
