### ISSUE TITLE
Jroll tab 标签切换问题！

### ISSUE THREAD

**Issue by uimom** [chjtx/JRoll#27]
runjs 地址：http://runjs.cn/detail/5gl4mw14

如果Tab1滚动条拖到最后还在回弹的时候，再点击Tab2，那么它就会停在Tab1的滚动位置里，而不会执行jroll.scrollTo(0,0)

请问这个有没有什么解决方法？

**Comment by chjtx** [comment]
可以建三个JRoll对象，不必每次都scrollTo(0, 0)

```html
<div class="jrollwrap">
  <ul id="u1"><li></li></ul>
  <ul id="u2"><li></li></ul>
  <ul id="u3"><li></li></ul>
</div>
```

```js
var j1 = new JRoll('.jrollwrap', {scroller: '#u1'})
var j2 = new JRoll('.jrollwrap', {scroller: '#u2'})
var j3 = new JRoll('.jrollwrap', {scroller: '#u3'})
```

**Comment by uimom** [comment]
这样操作太繁琐了，如果有十几个或更多这样的TAB标签，那么工程量会很大的~

**Comment by chjtx** [comment]
呃！！！将你的tab做成组件，每次只需调用一个方法就自动生成tab，根据你进入的参数创建tab标签个数，这样就方便多了

**Comment by uimom** [comment]
我是结合Swiper插件来使用的，这个TAB只是用来说明这个scrollTo(0, 0) BUG事件！
不能从根本上解决这个问题吗？
拜托了~~~~谢谢~~~

**Comment by chjtx** [comment]
使用姿势不对，不属于bug，不予处理，抱歉

**Comment by uimom** [comment]
呃！@_@，只是在使用你们这个插件中出现这样的一个问题，我在这里提出来！看看是不是你们这个插件的问题所有，既然你说不是，那就不是吧！
还是多谢你的~~~
