### ISSUE TITLE
仿QQ列表的一个问题！

### ISSUE THREAD

**Issue by thinkuid** [chjtx/JRoll#28]
for (var i=0,l=items.length; i<l; i++) {
            // 每行创建jroll实例
            var j = new JRoll(items[i], {
                scrollX:true,
                bounce:false
            });
}
--------------------------------------
a.列表                                        ...
--------------------------------------
a-1.列表(展开的内容)           
--------------------------------------
b.列表                                        ...
--------------------------------------
c.列表                                         ...
--------------------------------------

请问用 防QQ列表 for 方式，将删除换成一个展开更多形式的按钮，高度改变了，要怎样进行.refresh();

谢谢！~~~

**Comment by chjtx** [comment]
每个div.scroller都有索引指向其本身的jroll的

```html
<div id="w">
  <div id="s"></div>
</div>
<script>
var jroll = new JRoll('#w')
document.getElementById('s').jroll === jroll // true
</script>
```

官网示例的册除按钮的父元素就是这个`scroller`元素，获取它的jroll就可以了
