### ISSUE TITLE
下拉刷新问题

### ISSUE THREAD

**Issue by dreaminglwj** [chjtx/JRoll#3]
忘记了是什么问题了，好久以前发现的，自己改了代码，不知道github上有repo。
现在把代码位置贴上来，希望能有些帮助：
jroll-infinite.js中
function callback(data)函数
html += options.total === me.options.page ? options.completeTip : options.loadingTip;
改为
html += data.length == 0 ? options.completeTip : options.loadingTip;
好像是解决滑动的时候加载失败，但是计数却增加了的问题。改为以目前实际加载数量为准。
另外pages计数好像有逻辑问题。
ps：挺好的一个控件，希望能够一起贡献下

**Comment by chjtx** [comment]
@dreaminglwj 采纳，下个版本修复。世界需要你，一起加油

**Comment by dreaminglwj** [comment]
另外还有就是当列表元素少的装不满一屏的时候，图标的隐藏问题

**Comment by chjtx** [comment]
@dreaminglwj 哥们，我又审查了一遍代码，应该不会存在你说的问题

- 第一个callback的问题应该这样用：
```js
jroll.infinite({
  getData: function(page, callback) {
    ajax({
      url: "xxx?page=" + page,
      success: function(data) {
        if (data.status === 'success') {
          callback(data);
        } else {
          alert('请求失败！')
        }
      }
    });
  }
})
```
只有在后台返回的数据状态为success时才执行callback，jroll-infinite.js里的callback是没问题的

- 第二个不满一屏的问题：
不满一屏，表明page为1，total也为1，提示信息是显示“已全部加载完成”
如果不满一屏也将total设为大于1，那就是业务代码的问题了

**Comment by dreaminglwj** [comment]
那么问题就来了，如果后台没有数据了返回false，就不会调用callback，所以下面显示的提示就会是“加载中”，如果后台没有数据了返回为0个元素的数组，这时候刷新一次page增加1，这显然是不合理。所以建议在callback中判断，如果返回的数据长度为0做0的处理逻辑。

另外请教下，我在infinite的callback种没有找到请求的startindex的增加代码，那么在什么地方对startindex做的增加操作呢？

**Comment by dreaminglwj** [comment]
page的自增找到了。


另外有一个地方我觉得需要考虑一下，因为有可能有的列表数据比较少，却突然有个增加，比如评论，一片文章刚发出来，只有2条评论，而我的下拉刷新每页加载10条，在我已经加载了2条的时候，第三个人来评论了，这个时候，第3~10条评论肯定是加载不出来的，所以在最后一页未满的时候，再次刷新，应该重新加载最后一页，而不是加载后一页。

**Comment by cjlice** [comment]
第3条评论加载不出来也很合常理，这时需要配合下拉刷新，而不是单单一下上拉加载
