### ISSUE TITLE
无限加载bug

### ISSUE THREAD

**Issue by BobetaX** [chjtx/JRoll#30]
你好，最近在使用您开发的JRoll下拉插件，首先感谢你开发这个插件，确实比iscroll好用。
在此给您提一个bug，也算尽绵薄之力。
bug:在无限加载插件中，如果我向下滑动的过程中，突然向上滑动。插件会直接滚动到最下面，并出现一个大面积的空白页面。在您的官方文档中也有这个现象，是否可以在执行滑动任务前，插件判断下最大的滑动距离。从而避免这种现象？

**Comment by chjtx** [comment]
感谢反馈，请问是在什么型号设备上出现的问题？我用小米5自带浏览器和Mac的Chrome浏览器模拟器运行“无限加载”demo，滑到底部显示“正在加载...”的时候快速向上滑动并没有出现你描述的大片空白。

你说的大片空白是否开启了blank选项？如果你运行“自定义图标+开启blank”demo出现大片空白是正常现象，blank是空白的意思，即是将页面未在屏幕上的内容设为display:none以减轻浏览器渲染压力提升滑动效果，一般不需要开启该选项，在超大数据量列表展示极坏的情况下才会开启

但是开启blank选项也不会出现下滑过程中突然向上会直接滚动到最下面，是否在最新版`jroll v2.4.11` + `jroll-infinite v2.1.4`上出现的？
