### ISSUE TITLE
希望能搞个精简版的JRoll

### ISSUE THREAD

**Issue by singod** [chjtx/JRoll#31]
能不能搞个精简版的，动不动就20-30KB，对应手机端感觉还是大了一点，手机端也不需要太过复杂的功能，这个可以用来做手机端日期控件与下拉无限加载，希望能精简一个10几KB的版本，这个很有用，谢谢！如果每个控件都20-30KB，如果一个手机端的页面需要4-5个这样的控件，整体下来JS也是一个庞大体积的，对于手机端来说很是不划算的！

**Comment by chjtx** [comment]
这个建议不错，如果只包含垂直滑动确实可以减少不少代码，现在的压缩版也就15k，不大吧。忙完这边的事后满足你，搞个压缩后才几k的精简版

**Comment by chjtx** [comment]
@singod 精简版已出炉，说明文档：[https://github.com/chjtx/JRoll/blob/master/README-LITE.md](https://github.com/chjtx/JRoll/blob/master/README-LITE.md)

为了兼容下拉刷新和上拉加载扩展，压缩到10k，已至极限，再减就成半残品了
