### ISSUE TITLE
自动向上反弹的问题

### ISSUE THREAD

**Issue by lensh** [chjtx/JRoll#34]
您好，首先你的scroll要比iScroll好用多了，这是肯定的，不过我还是遇到了一个问题，就是在向下滑动并且松开手指的时候，此时还没有滑动到最底部，但是却自动向上反弹了，而且还是反弹到最顶部。这是为什么啊？

**Comment by chjtx** [comment]
@lensh 纯文字描述我也很头疼，能在[http://runjs.cn/](http://runjs.cn/)上搞个demo看看是怎样一回事吗？

**Comment by afenghy** [comment]
@lensh 大概这个效果：http://runjs.cn/detail/og1prhau
点击右下角黄色按扭

**Comment by chjtx** [comment]
@afenghy 都没有用到jroll，用个jquery来模拟效果，我能怎么办:joy:
