### ISSUE TITLE
关于上拉加载更多的小问题

### ISSUE THREAD

**Issue by alicksnake22** [chjtx/JRoll#35]
1、jroll.infinite这个函数，初始化的时候会自动执行一次吗？能取消自动执行吗?
2、为何执行下拉刷新的时候也会走一次jroll.infinite？
3、能否配合angular使用？我在scroller里面使用了angular-ngrepeat，如果在只加入jroll.pulldown的情况下，请求了angular数据后然后执行apply，再执行jroll.refresh数据是可以出现。至于同时加入pulldown和infinite的话，则angular数据无法显示，估计是infinite的template参数会覆盖掉scroller里面的html标签，这个有解吗？

**Comment by chjtx** [comment]
1、`jroll.infinite`这个扩展的getData函数初始化时是会自动执行一次，要取消自动执行这样判断一下就行了
```js
var first = true
jroll.infinite({
    getData: function(page, callback) {
        if (first) {
            first = false
        } else {
            // 执行你的代码
        }
    }
})
```

2、因为你的数据不满一屏，却用了分页，如果不满一屏的数据total应该是1，表示只有一页，如果多于一页就会发生上述现象

3、配合angular使用的话估计要自行使用JRoll写一个`jroll-angular-infinite`插件了，我不会angular，所以只写了个[jroll-vue-infinite](https://github.com/chjtx/JRoll/tree/master/extends/jroll-vue-infinite)，可以参考Vue的这个插件自己写个Angular的

**Comment by alicksnake22** [comment]
好的，谢谢，jroll不错
