### ISSUE TITLE
回弹有些生硬，松手后会有稍微的抖动

### ISSUE THREAD

**Issue by zhipingli** [chjtx/JRoll#37]
希望增加 衰减系数参数deceleration 灵活调节衰减系数，提高体验，接近原生app的回弹效果

**Comment by chjtx** [comment]
嗯，还没掌握这套回弹的算法，以后功力深厚了，一定改

**Comment by Wanghengfeng** [comment]
希望能加上一个scrollToElement方法，感觉会方便很多

**Comment by chjtx** [comment]
@Wanghengfeng 已发布JRoll v2.5.0，添加scrollToElement方法 [http://www.chjtx.com/JRoll/#download](http://www.chjtx.com/JRoll/#download)

**Comment by zncs520** [comment]
上拉加载 总页面数 能做在ajax请求返回 中么?

**Comment by chjtx** [comment]
@zncs520 可以动态修改的啊
