### ISSUE TITLE
jroll 与 Vue 集成的问题（jroll-vue-infinite）。

### ISSUE THREAD

**Issue by xiongmingwu** [chjtx/JRoll#38]
作者您好，目前使用 jroll-vue-infinite 发现有点不太适合，感觉该插件的使用方式与vue官方推荐的集成方式出入太大，且不方便。比如组件初始化(网络环境无法上传截图至github)：
`'jroll-infinite': JRoll.VueInfinite({
        bottomed() {
          var me = this;
          this.tip = '没有更多数据啦！'
          //if (me.page === 0) {
          this.productList.concat([1, 2, 3, 4, 5])
          me.success()
        },
        updated() {
          console.log('current page is ' + this.page)
        }
      })`
而您的回调函数 bottomed 中我无法获取我当前组件的变量，我看您的项目中也没有SPA这块的案例，能否提供相应的案例给出参考?

**Comment by xiongmingwu** [comment]
有计划改造下与vue的集成方式吗？比如参考Vux[https://github.com/airyland/vux](url)

**Comment by chjtx** [comment]
每个div.scroller都有索引指向其本身的jroll的

例：
```html
<div id="w">
  <div id="s"></div>
</div>
<script>
var jroll = new JRoll('#w')
document.getElementById('s').jroll === jroll // true
</script>
```

在jroll-vue-infinite里可以这样获取
```html
<jroll-infinite ref="myjroll"></jroll-infinite>
```
```js
{
  mounted() {
    this.$nextTick(() => {
      this.$refs.myjroll.$el.children[0].jroll.refresh()
    })
  }
}
```

`this.$refs.myjroll.$el.children[0].jroll`这样调用是有点冗长，因设计之初对vue还不是很熟，嗯，会参考下看看怎样改

SPA的话可以看看我的另一个项目JTaro，JTaro-UI是为JTaro开发的UI库，同时也是基于JTaro构建的项目，有兴趣可以看看，当然这个都是为方便我个人开发做的，成熟度不高

完整的小项目可以看下：[https://gitee.com/chenjianlong/weixinvote]（https://gitee.com/chenjianlong/weixinvote）

**Comment by chjtx** [comment]
https://github.com/chjtx/JRoll/tree/master/extends/jroll-vue-infinite2 新鲜出炉，第二版的使用方式应该会更符合vue组件规范 @xiongmingwu
