### ISSUE TITLE
抱歉，只能在这里咨询

### ISSUE THREAD

**Issue by hasbug** [chjtx/JRoll#4]
你好，无限加载我看到demo是用到了模板引擎。我用的是vue，能不能像下拉刷新那样，只是提供一个方法去触发我自己的分页加载事件，最后我自己处理完了，再refresh高度就好了，不需要模板引擎。

**Comment by chjtx** [comment]
在这里咨询是正确的。个人精力有限，只在周末有时间维护，没开QQ群什么的。
为vue写的无限加载：[jroll-vue-infinite](https://github.com/chjtx/JRoll/tree/master/extends/jroll-vue-infinite)
