### ISSUE TITLE
jroll回弹的时候，为什么回弹距离无法监听

### ISSUE THREAD

**Issue by little-buddy** [chjtx/JRoll#43]
作者你好，用你的jroll 模拟了下下拉刷新，但是在做下拉刷新动画的时候，下拉回弹的距离无法监听，这让让人很头疼，有解决的方案吗

**Comment by chjtx** [comment]
官网demo有下拉刷新的，你是想做什么样的下拉刷新？

**Comment by chjtx** [comment]
你是说加个onbounce事件，在触发回弹的时候执行？这个很好办，你看下源码，找到适当的地方改一下，然后将文件名加上自己的后缀以作区别。至于jroll.maxScrollY会少10个px，应该是布局问题，wrapper和scroller都用绝对定位试试。`new JRoll('#scroller', {id:'xxx'})`这样提供id创建的jroll是会复用的，不会每次都创建。可能通过react生成的组件会整个父dom替换，这样创建id也是没用的。我一向独来独往，没什么程序员交谈会的，倒是加了几个前端QQ群，基本上潜水。多研究一下别人的源码就行了，我是研究iscroll的源码写出jroll的，因当时用iscroll做一个滑动列表，在安卓机上列表上300条数据就卡爆了

**Comment by chjtx** [comment]
watch这个项目，在设置里将通知设置为发送到邮箱就可以接收到消息

**Comment by little-buddy** [comment]
作者难道不维护一下，添加个onBounce事件，这样用起来更灵活啊，我比较懒，很少看源码。哈哈，目前还在学框架这样的轮子

**Comment by chjtx** [comment]
不可能每个人叫我加什么就加什么的，不常用的功能不会加上去，不然我的jroll就变得很庞大了，由最初的12k增长到现在的35k，迫不得已分离出jroll-lite版。你不看源码那是你的事，跟我可没关系，我开源JRoll只是为了回馈社会，寻求心灵慰藉，哈哈
