### ISSUE TITLE
momentum为true的时候使用scrollTo强制滑动会有闪烁

### ISSUE THREAD

**Issue by eyelandlau** [chjtx/JRoll#45]
momentum为true，当我想做滑动吸附的时候  判断滚动方向然后直接scrollTo一个位置  会出现闪烁一下的问题

**Comment by chjtx** [comment]
可以在[http://runjs.cn/](http://runjs.cn/)搞个demo看看吗？

**Comment by eyelandlau** [comment]
http://runjs.cn/detail/mpxo84gm

不要用鼠标滚轮  用拖动或者触摸事件  我是写在移动端的

**Comment by chjtx** [comment]
因为momentum选项是开启惯性滑动，你释放手指时会自动滑动一段距离，同时你又用scrollTo指定它滑动一段距离，这样导致滑动冲突

**Comment by eyelandlau** [comment]
所以我觉得应该要有个beforeScroll的时机

**Comment by chjtx** [comment]
在scrollStart设jroll.options.momentum = false就可以了
