### ISSUE TITLE
上拉时手松开回到原处

### ISSUE THREAD

**Issue by xuweikang** [chjtx/JRoll#46]
上拉时手松开回到原处，这是为什么啊

**Comment by chjtx** [comment]
wrapper的高度和style的高度没设对

**Comment by xuweikang** [comment]
不对不对，我wrapper的高度确实是比scroller的高度低，样式和结构和作者你的pulldown demo一样的

**Comment by chjtx** [comment]
动态渲染数据的话在渲染完数据后要jroll.refresh()一下

**Comment by xuweikang** [comment]
@chjtx 找到原因了，是我初始化的位置不太对，导致dom还没渲染处来就实例了，谢谢。
