### ISSUE TITLE
加载所有数据后刷新，底部提示信息不正确

### ISSUE THREAD

**Issue by nemonicabin** [chjtx/JRoll#48]
jroll-vue-infinite.js 加载所有数据后刷新，底部提示信息不正确
请在后面加一点内容（修改成这样）：
watch: {
      page: function (p) {
        if (p === this.total) {
          this.tip = options.completeTip || '已全部加载完成'
        }else if(p < this.total){
          this.tip = options.tip
        }
      }
    }

**Comment by chjtx** [comment]
感谢反馈，已修复并发布：jroll-vue-infinite@0.1.1
