### ISSUE TITLE
加载大量数据卡顿

### ISSUE THREAD

**Issue by eyelandlau** [chjtx/JRoll#49]
用jroll做表格滚动时  因为dom节点非常多  滑动很卡  怎么破

**Comment by chjtx** [comment]
用table做的表格还是用ul>li做？有例子吗

**Comment by eyelandlau** [comment]
用table做的  已经解决了  强行去不渲染那些不再屏幕里的  主要是dom节点太多

**Comment by DearAKuan** [comment]
@eyelandlau  强行去不渲染那些不再屏幕里的.  请问这个是怎么做到的  我目前也碰到了这个问题 table过多 页面滚动卡顿

**Comment by eyelandlau** [comment]
这不就是判断元素是否在页面中  然后决定渲染不渲染么
