### ISSUE TITLE
使用jroll中，在iPhone上出现滚动后立刻回弹到其实位置

### ISSUE THREAD

**Issue by luyouxin84** [chjtx/JRoll#50]
就是能滑动，然后放手后，立刻回弹到了起始的位置。
目前只在iphone发现了这个问题。

是不是iPhone端的触摸事件不同导致的？

**Comment by chjtx** [comment]
这种情况一般是渲染机制不一样造成的，如果你setTimeout 500ms 后jroll.refresh可以解决该问题的话，证明你需要在数据渲染完成后的适当时机刷新一下jroll

**Comment by luyouxin84** [comment]
目前找到的原因是iphone写在vue mounted生命周期无效，需要写入到nexttick里边
还有，请问如果父元素用fixed定位，有没有影响呢？

**Comment by luyouxin84** [comment]
这个问题好头疼啊，因为滚动的高度和宽度是已经没问题了，但是transform里边的translate会在滑动后立即变为0，用scrollToElement也不能移动，整个translate都不会有变化。

**Comment by chjtx** [comment]
fixed没影响
