### ISSUE TITLE
请问在移动端惯性滚动的速度能调整吗，感觉速度慢的话有点抖动

### ISSUE THREAD

**Issue by w771854332** [chjtx/JRoll#52]
在Android和ios的qq浏览器，和iOS的Safari上都发现。惯性滚动的速度有点慢，并且快停下来的时候有抖动的现象。

请问大大这个能不能做优化的。我是配合React一起使用的

**Comment by chjtx** [comment]
在你的设备上跑跑官网的例子，如果没出现类似情况，这可能需要调整你的dom结构或者css样式。惯性速度只能通过修改源码去调整
