### ISSUE TITLE
既然是无限加载，其实就是不知道有多少页数的

### ISSUE THREAD

**Issue by shijunti19** [chjtx/JRoll#59]
既然是无限加载，其实就是不知道有多少页数的
那么你就不应该用total和page来判断是否完成，应该单独给一个
scrollBottom: function (page, success, error) {
改成
scrollBottom: function (page, success, error,finsh) {
finsh用作完成提示
完成的标志应该是没数据了

jroll-vue-infinite2.js
的加载提示应该支持传入，pc和wap的提示应该是不一样的

**Comment by chjtx** [comment]
total是可以动态修改的，如果不知道有多少页，可以设个999。一般没人能滑到999页。当后端返回数据告诉你已经结束了，再手动将total设为和page相等的值即可。

关于PC提示的问题，这就尴尬了，JRoll的定位只是解决移动端由其是android端使用div的overflow:auto时数据量大导致卡顿的问题，所以JRoll只为移动端设计的，PC端已经有很优秀的IScroll了

**Comment by shijunti19** [comment]
@chjtx 还有，一个页面是不是不能存在多个滚动div，我用table创建了多个，结果除了第一个，后面的都不行，这个可不可以支持。就是新闻列表那种。不能用一个，因为样式和数据都不同
