### ISSUE TITLE
微信端长按图片无法识别二维码

### ISSUE THREAD

**Issue by Xhyen** [chjtx/JRoll#6]
在scroll组件中，最后一个滚动对象添加内容是一张图片，然后长按图片无法识别，如果单独将图片拿出来不放入组件中则可以识别，请问下，是不是框架中阻止了长按屏幕的响应

**Comment by Xhyen** [comment]
没注意看，好像是框架监听了touch事件，导致长条的二维码图，手指长按事件只能在图中的一小部分实现，其他部分则被框架监拦截了。

**Comment by chjtx** [comment]
@Xhyen  我在微信查看带图片的demo，都能长按的，能不能做个小demo放在http://runjs.cn/上看看呢

**Comment by Xhyen** [comment]
@chjtx http://runjs.cn/code/wiweunjv 这是我的demo      'barCodeBg'为存放二维码的位置

**Comment by chjtx** [comment]
@Xhyen [http://www.chjtx.com/demo/jroll-issues6.html](http://www.chjtx.com/demo/jroll-issues6.html) 在微信上访问，二维码每个角都可长按

**Comment by Xhyen** [comment]
@chjtx 问题已经解决了，我检查了下代码，是我其中一段设置meta标签的代码导致的问题。

var docEl = document.documentElement;
var metaEl = document.querySelector('meta[name="viewport"]');
var dpr = window.devicePixelRatio || 1;
var scale = 1 / dpr;
               
//设置viewport，进行缩放，达到高清效果
metaEl.setAttribute('content', 'width=' + dpr * docEl.clientWidth + ',initial-scale=' + scale + ',maximum-scale=' + scale + ', minimum-scale=' + scale + ',user-scalable=no');

这段代码导致的。并不是你的组件问题。不好意思。是我没有看清。麻烦作者了。
