### ISSUE TITLE
小建议：功能与数据分离

### ISSUE THREAD

**Issue by wffkgoa** [chjtx/JRoll#66]
挺不错的组件，看了jroll-infinite.js，发现获取数据与scroll功能是绑在一起的，比如getData函数要首次加载数据，内部还提供了数据模板，这些都可以去掉，只提供纯粹的刷新和加载，至于用户下拉后怎么插入节点或修改节点，由用户在外部处理，处理完后complete一下就行了。

**Comment by chjtx** [comment]
:grin: 场景无限多，需求无限多，我是做不过来的啦，开源的目的是为了让用户能编写适合自己的插件，共同进步。你说的这个可以自己参考jroll-infinite.js编写一个jroll的插件的，加油吧
